import NavBar from "@/components/navBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>Profile</title>
            </head>
            <body className={inter.className}>
                <NavBar />
                <div className="m-4">
                    {children}
                </div>
            </body>
        </html>
    );
}