import Head from "next/head";
import NavBar from "@/components/navBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <>
           
            
            <NavBar />
            <div className="m-4">
                {children}
            </div>
        </>
    );
};

export default RootLayout;
